name: stayin_ubud
description: "A luxury vacation rental platform."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  supabase_flutter: ^2.3.0
  lucide_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
